### ISSUE TITLE
total number of items

### ISSUE THREAD

**Issue by imagenzm** [moody/Lootifications#10]
Is it possible to show the total number of items in the bag in parentheses?

**Comment by imagenzm** [comment]
![image](https://github.com/user-attachments/assets/9d63d62b-c860-4837-9ba2-634205a0ba40)
like this

**Comment by moody** [comment]
![image](https://github.com/user-attachments/assets/cd76a1ce-aff2-412f-acd6-fb0dd4a27f23)

Yeah, just tried it out. I'll probably add it as a toggle via chat command: `/lootifications count` or something similar.
